SELECT FLAVOR FROM 
(SELECT F.FLAVOR, F.TOTAL_ORDER + J.TOTAL_ORDER AS TOTAL_ORDER 
FROM FIRST_HALF F
INNER JOIN (
    SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER FROM JULY
    GROUP BY FLAVOR
) J ON J.FLAVOR = F.FLAVOR
ORDER BY TOTAL_ORDER DESC) NEW_TABLE
LIMIT 3;